### ISSUE TITLE
Error on docker compose 

### ISSUE THREAD

**Issue by tee2015** [KasperskyLab/klara#14]
### Subject of the issue
error on docker-compose up

### Your environment
Ubuntu 18.0
### Steps to reproduce
Tell us how to reproduce this issue.
sudo docker-compose up
### Expected behavior
Tell us what should happen
build the compose
### Actual behavior
Error on building container apt-get update failed and

**Comment by tee2015** [comment]
###To fix it please do the following
on kalara-dispatcher and klara-worker add to docker file the following:

RUN mkdir -p /etc/apt
COPY apt.conf /etc/apt

also ensure u get an apt.conf and place it on both dirs from your machine will do the job

Sudo docker-compose up

**Comment by xdanx** [comment]
Hey! Thanks for the issue.  As far as I know, I don't have steps on how to run klara into docker. You might be looking at another repo maybe :)
