### ISSUE TITLE
[ERROR] General failure when trying to insert the job in db: (1118, 'The size of BLOB/TEXT data inserted in one transaction is greater than 10% of redo log size. Increase the redo log size using innodb_log_file_size.')

### ISSUE THREAD

**Issue by Nono-m0le** [KasperskyLab/klara#23]
### Subject of the issue
Running a scan on 100k+ sample end up with :

[ERROR] General failure when trying to insert the job in db: (1118, 'The size of BLOB/TEXT data inserted in one transaction is greater than 10% of redo log size. Increase the redo log size using innodb_log_file_size.')

The job remained in "Assigned" and therefor can't be stop/removed from the UI. (It has to be done on the DB).

### Your environment
* your operating system : Ubuntu Server 18.04.2
* your Python version: Python 2.7.15+

### Steps to reproduce
Probably running an always true "dummy" rules on 100k+ sample : 
My dummy rule was similar to: 
`rule dummy_true {
condition:
true
}
`

### Expected behavior
A notification on the UI or anything that let us on a better state that this one (job still "assigned" but not running on the server)

### Actual behavior
Job remain in "Assigned", nothing happens on the server. Jobs has to be removed from the DB.

**Comment by xdanx** [comment]
Hello!

Unfortunately what you want is to insert 100k lines in a SQL BLOB/TEXT field which is not meant to store so much data. You need to limit the amount of data 1 worker sends to dispatcher.

`The job remained in "Assigned" and therefor can't be stop/removed from the UI. (It has to be done on the DB).`

Yes, I agree this is a separate issue and dispatcher/web interface should allow the user to remove  "hanging" jobs.
