### ISSUE TITLE
Installation suggestion and registration page

### ISSUE THREAD

**Issue by pe3zx** [KasperskyLab/klara#4]
Hi GReAT!

On [database setup document](https://github.com/KasperskyLab/klara/blob/master/install/database.md#database-requirements), running `cat * > db.schema.sql` can causes database error because wrong order on file concatenation (`2.4.1.txt` is appending before `2.4.txt`). This step may require some improvement.

After installation finished, I couldn't have found any registration page for WebUI and there is no sign about where can I register myself in.

**Comment by saweol** [comment]
There is no semicolon in config.sample.php. (Line 329 )

**Comment by xdanx** [comment]
Hey! yea, you are right. The setup page needs a little bit of improvement. I will update it in the next commit and let you know.

I'll also add info about how users management and how to login with the first user. Sorry for the lack of info.

**Comment by xdanx** [comment]
Fixed in commit 9dd6a220 . I have also added more documentation about features and users.

Hope this helps :)

*If this solved your problem, please go ahead and close the issue.*
