### ISSUE TITLE
cannot clone klara.git

### ISSUE THREAD

**Issue by cuckoo-linux** [KasperskyLab/klara#5]
aoa
receiving following errors:
git clone https://github.com:kasperskylab/klara.git ~/klara-github-repo
Cloning into '/home/cuckoo/klara-github-repo'...
fatal: repository 'https://github.com:kasperskylab/klara.git/' not found

**Comment by xdanx** [comment]
as @javadev pointed out, if you want to clone using https, you need to use URL 
`https://github.com/KasperskyLab/klara.git`
else, for SSH cloning you need to use
`git@github.com:KasperskyLab/klara.git`

Please check #9 as well
