### ISSUE TITLE
ERROR: Quota error! Your current quota stops you from adding 1 job(s)

### ISSUE THREAD

**Issue by taibaiyifeng** [KasperskyLab/klara#6]
when create new job,then have a error

**Comment by AndreyMironenkoGit** [comment]
Аналогичная проблема.
![image](https://user-images.githubusercontent.com/38126215/38408329-b566124c-3985-11e8-8ab9-15e32feb44b9.png)

**Comment by xdanx** [comment]
Hey, you need to create users that are either admins (`auth = 16`) or you need to setup a proper quota for users (not 0). 
Please check out https://github.com/KasperskyLab/klara/blob/master/install/features_web.md
