### ISSUE TITLE
dispacher not working

### ISSUE THREAD

**Issue by cuckoo-linux** [KasperskyLab/klara#7]
(klara)cuckoo@cuckoo-OptiPlex-9020:/var/projects/klara/dispatcher$ ./klara-dispatcher
bash: ./klara-dispatcher: Permission denied

**Comment by cuckoo-linux** [comment]
worker also not working
(klara)root@cuckoo-OptiPlex-9020:/var/projects/klara/worker# ./klara-worker
bash: ./klara-worker: Permission denied
not in cuckoo user and not as root

**Comment by xdanx** [comment]
Hey, can you provide more info about your issue? Can you show me your permissions for file 'klara-dispatcher':
`ls -l klara-dispatcher`

 I think this is an issue with permissions.

**Comment by cuckoo-linux** [comment]
(klara)root@cuckoo-OptiPlex-9020:/var/projects/klara/dispatcher# ls -l klara-dispatcher
-rw-r--r-- 1 root root 7353 Apr  4 11:04 klara-dispatcher

**Comment by cuckoo-linux** [comment]
now i am getting this error:
(klara)root@cuckoo-OptiPlex-9020:/var/projects/klara/dispatcher# ./klara-dispatcher
Traceback (most recent call last):
  File "./klara-dispatcher", line 5, in <module>
    import tornado.ioloop
ImportError: No module named tornado.ioloop

**Comment by xdanx** [comment]
Aha, I see. This means you don't have `tornado` module installed. Please carefully follow the steps in the install instructions: https://github.com/KasperskyLab/klara/tree/master/install

From your text I see you have the virtualenv (klara) enabled, so I guess you missed the step on installing dependencies:

`pip install -r requirements.txt`

**Comment by xdanx** [comment]
Hey, sorry but it seems this is a problem with your Python installation and not Klara related

**Comment by Nono-m0le** [comment]
In case you have multiple (interpreter) version of python installer, running a : 
`python -m pip install -r ~/klara-github-repo/install/requirements.txt`
instead of the described : 
`pip install -r ~/klara-github-repo/install/requirements.txt`

should do the trick / solve this issue.

**Comment by xdanx** [comment]
Hey, this might solve the issue, but the idea is to run `python` executable inside a virtual environment. 

As such, that env should have the desired python version and all the necessary tools :)

**Comment by Nono-m0le** [comment]
Thanks @xdanx however, by (almost strictly) following the install guide on a Ubuntu Server 18.04 it's not what I end up with. But I assume I probably do something wrong ...

**Comment by xdanx** [comment]
Hmm... Don't know what to say. We have a telegram group if you need help, check https://github.com/KasperskyLab/klara#contributing-and-reporting-issues
