### ISSUE TITLE
Parse error: syntax error, unexpected '$config' (T_VARIABLE) in application/config/config.php on line 382

### ISSUE THREAD

**Issue by DpoBoceka** [KasperskyLab/klara#8]
the problem occures after GETting the index.php page. The line contains:

$config['sess_driver'] = 'database';

Database's up. Table 'ci_session' exists. What's incorrect?

**Comment by hoboken515** [comment]
You likely didn't update this line in the configuration. Set the encryption key (I believe you can use any string) and add a semi colon to the end. The issue you're getting is syntax and not related to L382 at all. 
```
/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class, you must set an encryption key.
| See the user guide for more info.
|
| https://codeigniter.com/user_guide/libraries/encryption.html
|
*/

$config['encryption_key'] = ''
```

**Comment by xdanx** [comment]
@hoboken515 is right, there was a semicolon missing in the CI config file. I will fix it in the next commit. Meanwhile, remember to setup a strong encryption key https://www.codeigniter.com/user_guide/libraries/encryption.html#setting-your-encryption-key
